name: C++ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ cmake make
    - name: Create build directory
      run: mkdir -p tdlib_backend/build
    - name: Configure CMake
      run: cd tdlib_backend/build && cmake ..
    - name: Build
      run: cd tdlib_backend/build && make  > build.log 2>&1
    - name: Show build logs
      run: cat tdlib_backend/build/build.log
    - name: Compile TDLib FFI
      run: g++ -std=c++17 -shared -fPIC ../tdlib_ffi.cpp -o tdlib_backend/libtdlib_ffi.so -ltdjson
    - name: List build directory
      run: ls -lR tdlib_backend/build
    - name: Change permissions
      run: chmod +x tdlib_backend/build/vozletter_backend
    - name: Show CMakeCache.txt
      run: cat tdlib_backend/build/CMakeCache.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vozletter-backend
        path: |
          tdlib_backend/build/vozletter_backend
          tdlib_backend/libtdlib_ffi.so
